#include "types.h"

[uuid(0)]
interface TaskManager
{
    boolean NewTask(in Capability_t cap, in Thread_t pager, in Thread_t scheduler, out Capability_t newcap);
    boolean NewThread(in Capability_t cap, in Thread_t space, in Thread_t pager, in Thread_t scheduler, out Capability_t newcap);

    boolean DestroyTask(in Capability_t cap);
    boolean DestroyThread(in Capability_t cap);

    boolean RequestTaskDestroyNotification(in Capability_t cap);
    boolean RequestThreadDestroyNotification(in Capability_t cap);

    boolean GetMyCapability(out Capability_t newcap);
    boolean LessenCapability(in Capability_t cap, in Word_t flags, out Capability_t newcap);
};

